@echo off
rem Copie este arquivo para atualizarrefatorado.local.bat e preencha localmente.
rem O arquivo atualizarrefatorado.local.bat deve permanecer fora do Git.
rem Nao grave senha, token ou chave privada.

set "HOST=CONFIGURAR_HOST"
set "PORT=CONFIGURAR_PORT"
set "USER=CONFIGURAR_USER"

set "REMOTE_APP_DIR=CONFIGURAR_REMOTE_APP_DIR"
set "REMOTE_BACKEND_DIR=CONFIGURAR_REMOTE_BACKEND_DIR"
set "REMOTE_STATIC_DIR=CONFIGURAR_REMOTE_STATIC_DIR"
set "REMOTE_BAILEYS_DIR=CONFIGURAR_REMOTE_BAILEYS_DIR"
set "REMOTE_STAGING_DIR=CONFIGURAR_REMOTE_STAGING_DIR"
set "REMOTE_BACKUP_DIR=CONFIGURAR_REMOTE_BACKUP_DIR"
set "REMOTE_SERVER_BACKUP_DIR=CONFIGURAR_REMOTE_SERVER_BACKUP_DIR"

set "REMOTE_UNZIP_TOOL=python3 -m zipfile -e"
set "REMOTE_HASH_TOOL=sha256sum"
set "REMOTE_TAR_TOOL=tar"
set "REMOTE_SERVICE_RESTART=CONFIGURAR_REMOTE_SERVICE_RESTART"
set "HEALTHCHECK_URL="
set "APK_PUBLIC_BASE_URL="
